/**
 * LPU Map - Campus Relational Data Store
 * Ready for your custom campus datasets.
 */

// LPU Campus Center Coordinate
const CAMPUS_CENTER = [31.2536, 75.7037];

// ============================================================================
// 1. 🏛️ CAMPUS GROUPS (Departments, Food Courts, Clusters) - ADD YOURS HERE
// ============================================================================
const CAMPUS_GROUPS = [
  {
    id: "fashion-design-dept",
    name: "School of Fashion Design",
    category: "academics",
    type: "Department",
    tags: ["fashion design", "school of fashion design", "design department"],
    blocks: ["block-1-fashion-design"],
    centerCoords: [31.258597515534394, 75.70874010081363],
    desc: "Department of Fashion Design at LPU.",
    image: ""
  },
  {
    id: "cse-dept",
    name: "School of Computer Science & Engineering (CSE)",
    category: "academics",
    type: "Department Zone",
    tags: ["cse", "computer science", "it", "coding", "software", "btech cse", "cse blocks"],
    blocks: ["block-25", "block-26", "block-27", "block-28", "block-31", "block-32", "block-33", "block-34", "block-36", "block-37", "block-38"],
    centerCoords: [31.25252781150963, 75.7029864749583],
    desc: "Houses the School of Computer Science & Engineering.",
    image: ""
  }
  // --- TEMPLATE EXAMPLE (Add your own groups below) ---
  //   {
  //     id: "cse-dept",
  //     name: "School of Computer Science & Engineering (CSE)",
  //     category: "academics", // 'academics' | 'hostels' | 'food' | 'parking' | 'offices' | 'healthcare' | 'others'
  //     type: "Department Zone",
  //     tags: ["cse", "computer science", "it", "coding", "software", "btech cse", "cse blocks"],
  //     blocks: ["block-25", "block-28"], // List of child block IDs
  //     centerCoords: [31.2546, 75.7031],
  //     desc: "Houses the School of Computer Science & Engineering.",
  //     image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=600"
  //   }
];

// // ============================================================================
// // 2. 📍 INDIVIDUAL CAMPUS LOCATIONS (Blocks, Labs, Shops) - ADD YOURS HERE
// // ============================================================================
var CAMPUS_LOCATIONS = window.CAMPUS_LOCATIONS = [
  // --- Main Gates ---
  {
    id: "main-gate-vehicle",
    name: "Main Gate (Vehicles)",
    groupId: null,
    groupName: null,
    category: "parking",
    type: "Campus Entrance",
    lat: 31.260758,
    lng: 75.706920,
    floor: "Roadway Checkpoint",
    facilities: ["Security Post", "Vehicle Boom Barrier"],
    tags: ["main gate", "vehicle gate", "car entry", "gate", "entry"],
    desc: "Primary entrance and exit gate for vehicles.",
    hours: "Open 24 Hours",
    phone: "",
    image: ""
  },
  {
    id: "main-gate-parking",
    name: "LPU Main Gate Parking",
    groupId: null,
    groupName: null,
    category: "parking",
    type: "Parking Area",
    lat: 31.259813520055438,
    lng: 75.70608609956477,
    floor: "Ground Level",
    facilities: ["Vehicle Parking", "Security Post"],
    tags: ["lpu main gate parking", "main gate parking", "parking", "vehicle parking"],
    desc: "Parking area near the LPU main gate.",
    hours: "Open 24 Hours",
    phone: "",
    image: ""
  },
  {
    id: "baldev-raj-mittal-park",
    name: "Baldev Raj Mittal Park",
    groupId: null,
    groupName: null,
    category: "others",
    type: "Park",
    lat: 31.258972708092458,
    lng: 75.70693781562309,
    floor: "Ground Level",
    facilities: ["Green Space", "Seating Area"],
    tags: ["baldev raj mittal park", "park", "garden", "green space"],
    desc: "Baldev Raj Mittal Park on the LPU campus.",
    hours: "Open on Campus Schedule",
    phone: "",
    image: ""
  },
  {
    id: "sh-baldevraj-mittal-auditorium",
    name: "Sh. Baldevraj Mittal Auditorium",
    groupId: null,
    groupName: null,
    category: "others",
    type: "Auditorium",
    lat: 31.258442490636092,
    lng: 75.70785810764602,
    floor: "Ground Level",
    facilities: ["Auditorium Hall", "Event Venue"],
    tags: ["sh baldevraj mittal auditorium", "baldevraj mittal auditorium", "auditorium", "event venue"],
    desc: "Sh. Baldevraj Mittal Auditorium on the LPU campus.",
    hours: "Open on Campus Schedule",
    phone: "",
    image: ""
  },
  {
    id: "block-1",
    name: "Block 1",
    groupId: "fashion-design-dept",
    groupName: "School of Fashion Design",
    category: "academics",
    type: "Academic Block",
    lat: 31.258597515534394,
    lng: 75.70874010081363,
    floor: "Academic Block",
    facilities: ["Classrooms", "Design Studios", "Faculty Offices"],
    tags: ["block 1", "block-1", "school of fashion design", "fashion design", "academic block"],
    desc: "Block 1 houses the School of Fashion Design on the LPU campus.",
    hours: "Open on Campus Schedule",
    phone: "",
    image: ""
  },
  {
    id: "uni-health-center",
    name: "Uni Health Center",
    groupId: null,
    groupName: null,
    category: "healthcare",
    type: "Health Center",
    lat: 31.258119604214023,
    lng: 75.70674904051353,
    floor: "Ground Level",
    facilities: ["Medical Assistance", "First Aid", "Doctor Consultation"],
    tags: ["uni health center", "health center", "medical center", "first aid", "healthcare"],
    desc: "Uni Health Center providing healthcare services on the LPU campus.",
    hours: "Open on Campus Schedule",
    phone: "",
    image: ""
  },
  {
    id: "block-25",
    name: "Block 25 (CSE)",
    groupId: "cse-dept",
    groupName: "School of Computer Science & Engineering (CSE)",
    category: "academics",
    type: "Academic Block",
    lat: 31.25285938442377,
    lng: 75.70247885462516,
    floor: "Multi-storey Block",
    facilities: ["Classrooms", "Computer Labs", "Faculty Cabins"],
    tags: ["block 25", "cse", "computer science", "b25", "academic block"],
    desc: "Block 25 - Department of Computer Science & Engineering.",
    hours: "8:00 AM - 5:30 PM",
    phone: "",
    image: ""
  },
  {
    id: "block-26",
    name: "Block 26 (CSE)",
    groupId: "cse-dept",
    groupName: "School of Computer Science & Engineering (CSE)",
    category: "academics",
    type: "Academic Block",
    lat: 31.252861883513926,
    lng: 75.70289512306216,
    floor: "Multi-storey Block",
    facilities: ["Classrooms", "Computer Labs", "Faculty Cabins"],
    tags: ["block 26", "cse", "computer science", "b26", "academic block"],
    desc: "Block 26 - Department of Computer Science & Engineering.",
    hours: "8:00 AM - 5:30 PM",
    phone: "",
    image: ""
  },
  {
    id: "block-27",
    name: "Block 27 (CSE)",
    groupId: "cse-dept",
    groupName: "School of Computer Science & Engineering (CSE)",
    category: "academics",
    type: "Academic Block",
    lat: 31.252858651898666,
    lng: 75.70330718355343,
    floor: "Multi-storey Block",
    facilities: ["Classrooms", "Computer Labs", "Faculty Cabins"],
    tags: ["block 27", "cse", "computer science", "b27", "academic block"],
    hours: "8:00 AM - 5:30 PM",
    phone: "",
    image: ""
  },
  {
    id: "block-28",
    name: "Block 28 (CSE)",
    groupId: "cse-dept",
    groupName: "School of Computer Science & Engineering (CSE)",
    category: "academics",
    type: "Academic Block",
    lat: 31.25284540741938,
    lng: 75.70373386456326,
    floor: "Multi-storey Block",
    facilities: ["Classrooms", "Computer Labs", "Faculty Cabins"],
    tags: ["block 28", "cse", "computer science", "b28", "academic block"],
    desc: "Block 28 - Department of Computer Science & Engineering.",
    hours: "8:00 AM - 5:30 PM",
    phone: "",
    image: ""
  },
  {
    id: "block-32",
    name: "Block 32 (Admin)",
    groupId: "cse-dept",
    groupName: "School of Computer Science & Engineering (CSE)",
    category: "academics",
    type: "Academic Block",
    lat: 31.252169312144662,
    lng: 75.70476168618337,
    floor: "Multi-storey Block",
    facilities: ["Classrooms", "Computer Labs", "Faculty Cabins"],
    tags: ["block 32", "cse", "computer science", "b32", "academic block"],
    desc: "Block 32 - Department of Computer Science & Engineering.",
    hours: "8:00 AM - 5:30 PM",
    phone: "",
    image: ""
  },
  {
    id: "block-33",
    name: "Block 33 (CSE)",
    groupId: "cse-dept",
    groupName: "School of Computer Science & Engineering (CSE)",
    category: "academics",
    type: "Academic Block",
    lat: 31.25182752424929,
    lng: 75.70475097721261,
    floor: "Multi-storey Block",
    facilities: ["Classrooms", "Computer Labs", "Faculty Cabins"],
    tags: ["block 33", "cse", "computer science", "b33", "academic block"],
    desc: "Block 33 - Department of Computer Science & Engineering.",
    hours: "8:00 AM - 5:30 PM",
    phone: "",
    image: ""
  },
  {
    id: "block-34",
    name: "Block 34 (CSE)",
    groupId: "cse-dept",
    groupName: "School of Computer Science & Engineering (CSE)",
    category: "academics",
    type: "Academic Block",
    lat: 31.25148864838823,
    lng: 75.7047360500708,
    floor: "Multi-storey Block",
    facilities: ["Classrooms", "Computer Labs", "Faculty Cabins"],
    tags: ["block 34", "cse", "computer science", "b34", "academic block"],
    desc: "Block 34 - Department of Computer Science & Engineering.",
    hours: "8:00 AM - 5:30 PM",
    phone: "",
    image: ""
  },
  {
    id: "block-36",
    name: "Block 36 (CSE)",
    groupId: "cse-dept",
    groupName: "School of Computer Science & Engineering (CSE)",
    category: "academics",
    type: "Academic Block",
    lat: 31.2516333779156,
    lng: 75.70412763243169,
    floor: "Multi-storey Block",
    facilities: ["Classrooms", "Computer Labs", "Faculty Cabins"],
    tags: ["block 36", "cse", "computer science", "b36", "academic block"],
    desc: "Block 36 - Department of Computer Science & Engineering.",
    hours: "8:00 AM - 5:30 PM",
    phone: "",
    image: ""
  },
  {
    id: "block-37",
    name: "Block 37 (CSE)",
    groupId: "cse-dept",
    groupName: "School of Computer Science & Engineering (CSE)",
    category: "academics",
    type: "Academic Block",
    lat: 31.251858851005732,
    lng: 75.70373201751212,
    floor: "Multi-storey Block",
    facilities: ["Classrooms", "Computer Labs", "Faculty Cabins"],
    tags: ["block 37", "cse", "computer science", "b37", "academic block"],
    desc: "Block 37 - Department of Computer Science & Engineering.",
    hours: "8:00 AM - 5:30 PM",
    phone: "",
    image: ""
  },
  {
    id: "block-38",
    name: "Block 38 (CSE)",
    groupId: "cse-dept",
    groupName: "School of Computer Science & Engineering (CSE)",
    category: "academics",
    type: "Academic Block",
    lat: 31.252140287536804,
    lng: 75.70338135340346,
    floor: "Multi-storey Block",
    facilities: ["Classrooms", "Computer Labs", "Faculty Cabins"],
    tags: ["block 38", "cse", "computer science", "b38", "academic block"],
    desc: "Block 38 - Department of Computer Science & Engineering.",
    hours: "8:00 AM - 5:30 PM",
    phone: "",
    image: ""
  },
  {
    id: "block-31",
    name: "Block 31 (Admin)",
    groupId: "cse-dept",
    groupName: "School of Computer Science & Engineering (CSE)",
    category: "offices",
    type: "Administrative & Academic Block",
    lat: 31.252443962233237,
    lng: 75.70496872629623,
    floor: "Multi-storey Block",
    facilities: ["Administrative Offices", "Classrooms", "Computer Labs", "Faculty Cabins"],
    tags: ["block 31", "admin", "administration", "cse", "computer science", "b31", "administrative block"],
    desc: "Block 31 - Administrative Block & CSE Department.",
    hours: "8:00 AM - 5:30 PM",
    phone: "",
    image: ""
  },
  {
    id: "main-gate-students",
    name: "Main Gate (Students)",
    groupId: null,
    groupName: null,
    category: "others",
    type: "Pedestrian Gate",
    lat: 31.260585,    // 31°15'38.0"N
    lng: 75.707280,    // 75°42'26.1"E
    floor: "Pedestrian Entry",
    facilities: ["RFID Turnstiles", "Security Guardhouse"],
    tags: ["student gate", "main gate", "pedestrian", "entry", "gate"],
    desc: "Main pedestrian entry for students and staff.",
    hours: "Open 24 Hours",
    phone: "",
    image: ""
  }
];

// ============================================================================
// 3. 🏢 CAMPUS OFFICES (Shown on the map only at block-level zoom) - ADD YOURS HERE
// ============================================================================
var CAMPUS_OFFICES = window.CAMPUS_OFFICES = [
  {
    id: "office-admin-28-209",
    name: "Administrative Office (Block 28, Room 209)",
    groupId: "cse-dept",
    groupName: "School of Computer Science & Engineering (CSE)",
    category: "offices",
    type: "Administrative Office",
    parentBlockIds: ["block-27", "block-28"],
    visibleFromZoom: 19,
    lat: 31.252754224964615,
    lng: 75.70378526355849,
    floor: "Second Floor, Room 209",
    facilities: ["Lost and Found", "Infrastructure Queries", "Faculty Details", "General Queries"],
    tags: ["administrative office", "admin office", "block 27", "block 28", "room 209", "lost and found", "infrastructure", "faculty details", "general queries"],
    desc: "Administrative office serving Blocks 27 and 28 for lost and found, infrastructure queries, faculty details, and general queries.",
    hours: "8:00 AM - 5:30 PM",
    phone: "",
    image: ""
  },
  {
    "id": "office-person-17442-arun-malik",
    "name": "Dr. Arun Malik",
    "uid": "17442",
    "designation": "Professor & Associate Dean",
    "responsibility": "HOS",
    "role": "HOS",
    "department_or_subject": null,
    "block": "27",
    "room": "201",
    "seating": null,
    "office": "HOS Office",
    "location_notation": "27-201",
    "parentBlockIds": [
      "block-27"
    ],
    "groupId": "cse-dept",
    "groupName": "School of Computing and Artificial Intelligence",
    "category": "offices",
    "type": "Head of School (HOS) Office",
    "lat": 31.252858651898666,
    "lng": 75.70330718355343,
    "visibleFromZoom": 19,
    "floor": "Block 27, Room 201, HOS Office",
    "facilities": [
      "Block 27 Academic Block",
      "HOS Office"
    ],
    "tags": [
      "17442",
      "201",
      "27 201",
      "27-201",
      "arun",
      "arun malik",
      "b27",
      "block 27",
      "block 27 room 201",
      "block-27",
      "dr. arun malik",
      "head of school",
      "hos",
      "hos office",
      "malik",
      "professor & associate dean",
      "room 201",
      "room 201 block 27",
      "room 201 of block 27",
      "uid 17442"
    ],
    "desc": "Dr. Arun Malik, Professor & Associate Dean. Role: HOS. Office: HOS Office. Located in Block 27, Room 201, HOS Office (Notation: 27-201).",
    "hours": "8:00 AM - 5:30 PM",
    "phone": "",
    "image": ""
  },
  {
    "id": "office-person-22078-baljit-singh-saini",
    "name": "Dr. Baljit Singh Saini",
    "uid": "22078",
    "designation": "Professor",
    "responsibility": "COD",
    "role": "COD",
    "department_or_subject": null,
    "block": "27",
    "room": "203",
    "seating": "C3",
    "office": null,
    "location_notation": "27-203-C3",
    "parentBlockIds": [
      "block-27"
    ],
    "groupId": "cse-dept",
    "groupName": "School of Computing and Artificial Intelligence",
    "category": "offices",
    "type": "Coordinator of Department (COD) Office",
    "lat": 31.252858651898666,
    "lng": 75.70330718355343,
    "visibleFromZoom": 19,
    "floor": "Block 27, Room 203, Cabin C3",
    "facilities": [
      "Block 27 Academic Block",
      "COD"
    ],
    "tags": [
      "203",
      "22078",
      "27 203 c3",
      "27-203-c3",
      "b27",
      "baljit",
      "baljit singh saini",
      "block 27",
      "block 27 room 203",
      "block-27",
      "c3",
      "cabin c3",
      "cod",
      "coordinator of department",
      "dr. baljit singh saini",
      "professor",
      "room 203",
      "room 203 block 27",
      "room 203 of block 27",
      "saini",
      "seating c3",
      "singh",
      "uid 22078"
    ],
    "desc": "Dr. Baljit Singh Saini, Professor. Role: COD. Located in Block 27, Room 203, Cabin C3 (Notation: 27-203-C3).",
    "hours": "8:00 AM - 5:30 PM",
    "phone": "",
    "image": ""
  },
  {
    "id": "office-person-12301-rajeev-kumar-patial",
    "name": "Dr. Rajeev Kumar Patial",
    "uid": "12301",
    "designation": "Associate Professor",
    "responsibility": "COD",
    "role": "COD",
    "department_or_subject": null,
    "block": "28",
    "room": "206",
    "seating": "C1",
    "office": null,
    "location_notation": "28-206-C1",
    "parentBlockIds": [
      "block-28"
    ],
    "groupId": "cse-dept",
    "groupName": "School of Computing and Artificial Intelligence",
    "category": "offices",
    "type": "Coordinator of Department (COD) Office",
    "lat": 31.25284540741938,
    "lng": 75.70373386456326,
    "visibleFromZoom": 19,
    "floor": "Block 28, Room 206, Cabin C1",
    "facilities": [
      "Block 28 Academic Block",
      "COD"
    ],
    "tags": [
      "12301",
      "206",
      "28 206 c1",
      "28-206-c1",
      "associate professor",
      "b28",
      "block 28",
      "block 28 room 206",
      "block-28",
      "c1",
      "cabin c1",
      "cod",
      "coordinator of department",
      "dr. rajeev kumar patial",
      "kumar",
      "patial",
      "rajeev",
      "rajeev kumar patial",
      "room 206",
      "room 206 block 28",
      "room 206 of block 28",
      "seating c1",
      "uid 12301"
    ],
    "desc": "Dr. Rajeev Kumar Patial, Associate Professor. Role: COD. Located in Block 28, Room 206, Cabin C1 (Notation: 28-206-C1).",
    "hours": "8:00 AM - 5:30 PM",
    "phone": "",
    "image": ""
  },
  {
    "id": "office-person-11530-harminder-singh-saggu",
    "name": "Dr. Harminder Singh Saggu",
    "uid": "11530",
    "designation": "Professor",
    "responsibility": "COD",
    "role": "COD",
    "department_or_subject": null,
    "block": "28",
    "room": "206",
    "seating": "C3",
    "office": null,
    "location_notation": "28-206-C3",
    "parentBlockIds": [
      "block-28"
    ],
    "groupId": "cse-dept",
    "groupName": "School of Computing and Artificial Intelligence",
    "category": "offices",
    "type": "Coordinator of Department (COD) Office",
    "lat": 31.25284540741938,
    "lng": 75.70373386456326,
    "visibleFromZoom": 19,
    "floor": "Block 28, Room 206, Cabin C3",
    "facilities": [
      "Block 28 Academic Block",
      "COD"
    ],
    "tags": [
      "11530",
      "206",
      "28 206 c3",
      "28-206-c3",
      "b28",
      "block 28",
      "block 28 room 206",
      "block-28",
      "c3",
      "cabin c3",
      "cod",
      "coordinator of department",
      "dr. harminder singh saggu",
      "harminder",
      "harminder singh saggu",
      "professor",
      "room 206",
      "room 206 block 28",
      "room 206 of block 28",
      "saggu",
      "seating c3",
      "singh",
      "uid 11530"
    ],
    "desc": "Dr. Harminder Singh Saggu, Professor. Role: COD. Located in Block 28, Room 206, Cabin C3 (Notation: 28-206-C3).",
    "hours": "8:00 AM - 5:30 PM",
    "phone": "",
    "image": ""
  },
  {
    "id": "office-person-28260-simarjit-singh-malhi",
    "name": "Dr. Simarjit Singh Malhi",
    "uid": "28260",
    "designation": "Associate Professor",
    "responsibility": "COD",
    "role": "COD",
    "department_or_subject": null,
    "block": "27",
    "room": "205",
    "seating": "C1",
    "office": null,
    "location_notation": "27-205-C1",
    "parentBlockIds": [
      "block-27"
    ],
    "groupId": "cse-dept",
    "groupName": "School of Computing and Artificial Intelligence",
    "category": "offices",
    "type": "Coordinator of Department (COD) Office",
    "lat": 31.252858651898666,
    "lng": 75.70330718355343,
    "visibleFromZoom": 19,
    "floor": "Block 27, Room 205, Cabin C1",
    "facilities": [
      "Block 27 Academic Block",
      "COD"
    ],
    "tags": [
      "205",
      "27 205 c1",
      "27-205-c1",
      "28260",
      "associate professor",
      "b27",
      "block 27",
      "block 27 room 205",
      "block-27",
      "c1",
      "cabin c1",
      "cod",
      "coordinator of department",
      "dr. simarjit singh malhi",
      "malhi",
      "room 205",
      "room 205 block 27",
      "room 205 of block 27",
      "seating c1",
      "simarjit",
      "simarjit singh malhi",
      "singh",
      "uid 28260"
    ],
    "desc": "Dr. Simarjit Singh Malhi, Associate Professor. Role: COD. Located in Block 27, Room 205, Cabin C1 (Notation: 27-205-C1).",
    "hours": "8:00 AM - 5:30 PM",
    "phone": "",
    "image": ""
  },
  {
    "id": "office-person-34813-sourabh-kaul",
    "name": "Mr. Sourabh Kaul",
    "uid": "34813",
    "designation": "Administrator",
    "responsibility": "Administrator",
    "role": "Administrator",
    "department_or_subject": null,
    "block": "27",
    "room": "206",
    "seating": null,
    "office": "Administrator Office",
    "location_notation": "27-206",
    "parentBlockIds": [
      "block-27"
    ],
    "groupId": "cse-dept",
    "groupName": "School of Computing and Artificial Intelligence",
    "category": "offices",
    "type": "Administrator Office",
    "lat": 31.252858651898666,
    "lng": 75.70330718355343,
    "visibleFromZoom": 19,
    "floor": "Block 27, Room 206, Administrator Office",
    "facilities": [
      "Block 27 Academic Block",
      "Administrator Office"
    ],
    "tags": [
      "206",
      "27 206",
      "27-206",
      "34813",
      "admin",
      "administration",
      "administrator",
      "administrator office",
      "b27",
      "block 27",
      "block 27 room 206",
      "block-27",
      "kaul",
      "mr. sourabh kaul",
      "room 206",
      "room 206 block 27",
      "room 206 of block 27",
      "sourabh",
      "sourabh kaul",
      "uid 34813"
    ],
    "desc": "Mr. Sourabh Kaul, Administrator. Role: Administrator. Office: Administrator Office. Located in Block 27, Room 206, Administrator Office (Notation: 27-206).",
    "hours": "8:00 AM - 5:30 PM",
    "phone": "",
    "image": ""
  },
  {
    "id": "office-person-16717-chirag-sharma",
    "name": "Dr. Chirag Sharma",
    "uid": "16717",
    "designation": "Associate Professor",
    "responsibility": "COD",
    "role": "COD",
    "department_or_subject": null,
    "block": "27",
    "room": "207",
    "seating": "C1",
    "office": null,
    "location_notation": "27-207-C1",
    "parentBlockIds": [
      "block-27"
    ],
    "groupId": "cse-dept",
    "groupName": "School of Computing and Artificial Intelligence",
    "category": "offices",
    "type": "Coordinator of Department (COD) Office",
    "lat": 31.252858651898666,
    "lng": 75.70330718355343,
    "visibleFromZoom": 19,
    "floor": "Block 27, Room 207, Cabin C1",
    "facilities": [
      "Block 27 Academic Block",
      "COD"
    ],
    "tags": [
      "16717",
      "207",
      "27 207 c1",
      "27-207-c1",
      "associate professor",
      "b27",
      "block 27",
      "block 27 room 207",
      "block-27",
      "c1",
      "cabin c1",
      "chirag",
      "chirag sharma",
      "cod",
      "coordinator of department",
      "dr. chirag sharma",
      "room 207",
      "room 207 block 27",
      "room 207 of block 27",
      "seating c1",
      "sharma",
      "uid 16717"
    ],
    "desc": "Dr. Chirag Sharma, Associate Professor. Role: COD. Located in Block 27, Room 207, Cabin C1 (Notation: 27-207-C1).",
    "hours": "8:00 AM - 5:30 PM",
    "phone": "",
    "image": ""
  },
  {
    "id": "office-person-17688-richa-jain",
    "name": "Dr. Richa Jain",
    "uid": "17688",
    "designation": "Associate Professor",
    "responsibility": "COD",
    "role": "COD",
    "department_or_subject": null,
    "block": "27",
    "room": "209",
    "seating": "C1",
    "office": null,
    "location_notation": "27-209-C1",
    "parentBlockIds": [
      "block-27"
    ],
    "groupId": "cse-dept",
    "groupName": "School of Computing and Artificial Intelligence",
    "category": "offices",
    "type": "Coordinator of Department (COD) Office",
    "lat": 31.252858651898666,
    "lng": 75.70330718355343,
    "visibleFromZoom": 19,
    "floor": "Block 27, Room 209, Cabin C1",
    "facilities": [
      "Block 27 Academic Block",
      "COD"
    ],
    "tags": [
      "17688",
      "209",
      "27 209 c1",
      "27-209-c1",
      "associate professor",
      "b27",
      "block 27",
      "block 27 room 209",
      "block-27",
      "c1",
      "cabin c1",
      "cod",
      "coordinator of department",
      "dr. richa jain",
      "jain",
      "richa",
      "richa jain",
      "room 209",
      "room 209 block 27",
      "room 209 of block 27",
      "seating c1",
      "uid 17688"
    ],
    "desc": "Dr. Richa Jain, Associate Professor. Role: COD. Located in Block 27, Room 209, Cabin C1 (Notation: 27-209-C1).",
    "hours": "8:00 AM - 5:30 PM",
    "phone": "",
    "image": ""
  },
  {
    "id": "office-person-17673-amritpal-singh",
    "name": "Dr. Amritpal Singh",
    "uid": "17673",
    "designation": "Associate Professor",
    "responsibility": "COD",
    "role": "COD",
    "department_or_subject": null,
    "block": "27",
    "room": "102",
    "seating": "C1",
    "office": null,
    "location_notation": "27-102-C1",
    "parentBlockIds": [
      "block-27"
    ],
    "groupId": "cse-dept",
    "groupName": "School of Computing and Artificial Intelligence",
    "category": "offices",
    "type": "Coordinator of Department (COD) Office",
    "lat": 31.252858651898666,
    "lng": 75.70330718355343,
    "visibleFromZoom": 19,
    "floor": "Block 27, Room 102, Cabin C1",
    "facilities": [
      "Block 27 Academic Block",
      "COD"
    ],
    "tags": [
      "102",
      "17673",
      "27 102 c1",
      "27-102-c1",
      "amritpal",
      "amritpal singh",
      "associate professor",
      "b27",
      "block 27",
      "block 27 room 102",
      "block-27",
      "c1",
      "cabin c1",
      "cod",
      "coordinator of department",
      "dr. amritpal singh",
      "room 102",
      "room 102 block 27",
      "room 102 of block 27",
      "seating c1",
      "singh",
      "uid 17673"
    ],
    "desc": "Dr. Amritpal Singh, Associate Professor. Role: COD. Located in Block 27, Room 102, Cabin C1 (Notation: 27-102-C1).",
    "hours": "8:00 AM - 5:30 PM",
    "phone": "",
    "image": ""
  },
  {
    "id": "office-person-15980-mohit-arora",
    "name": "Dr. Mohit Arora",
    "uid": "15980",
    "designation": "Associate Professor",
    "responsibility": "COD",
    "role": "COD",
    "department_or_subject": null,
    "block": "27",
    "room": "102",
    "seating": "C3",
    "office": null,
    "location_notation": "27-102-C3",
    "parentBlockIds": [
      "block-27"
    ],
    "groupId": "cse-dept",
    "groupName": "School of Computing and Artificial Intelligence",
    "category": "offices",
    "type": "Coordinator of Department (COD) Office",
    "lat": 31.252858651898666,
    "lng": 75.70330718355343,
    "visibleFromZoom": 19,
    "floor": "Block 27, Room 102, Cabin C3",
    "facilities": [
      "Block 27 Academic Block",
      "COD"
    ],
    "tags": [
      "102",
      "15980",
      "27 102 c3",
      "27-102-c3",
      "arora",
      "associate professor",
      "b27",
      "block 27",
      "block 27 room 102",
      "block-27",
      "c3",
      "cabin c3",
      "cod",
      "coordinator of department",
      "dr. mohit arora",
      "mohit",
      "mohit arora",
      "room 102",
      "room 102 block 27",
      "room 102 of block 27",
      "seating c3",
      "uid 15980"
    ],
    "desc": "Dr. Mohit Arora, Associate Professor. Role: COD. Located in Block 27, Room 102, Cabin C3 (Notation: 27-102-C3).",
    "hours": "8:00 AM - 5:30 PM",
    "phone": "",
    "image": ""
  },
  {
    "id": "office-person-11265-dalwinder-singh",
    "name": "Dr. Dalwinder Singh",
    "uid": "11265",
    "designation": "Professor/Deputy Director",
    "responsibility": "COS",
    "role": "COS",
    "department_or_subject": null,
    "block": "28",
    "room": "201A",
    "seating": null,
    "office": "COS Office",
    "location_notation": "28-201A",
    "parentBlockIds": [
      "block-28"
    ],
    "groupId": "cse-dept",
    "groupName": "School of Computing and Artificial Intelligence",
    "category": "offices",
    "type": "Coordinator of School (COS) Office",
    "lat": 31.25284540741938,
    "lng": 75.70373386456326,
    "visibleFromZoom": 19,
    "floor": "Block 28, Room 201A, COS Office",
    "facilities": [
      "Block 28 Academic Block",
      "COS Office"
    ],
    "tags": [
      "11265",
      "201a",
      "28 201a",
      "28-201a",
      "b28",
      "block 28",
      "block 28 room 201a",
      "block-28",
      "coordinator of school",
      "cos",
      "cos office",
      "dalwinder",
      "dalwinder singh",
      "dr. dalwinder singh",
      "professor/deputy director",
      "room 201A",
      "room 201a block 28",
      "room 201a of block 28",
      "singh",
      "uid 11265"
    ],
    "desc": "Dr. Dalwinder Singh, Professor/Deputy Director. Role: COS. Office: COS Office. Located in Block 28, Room 201A, COS Office (Notation: 28-201A).",
    "hours": "8:00 AM - 5:30 PM",
    "phone": "",
    "image": ""
  },
  {
    "id": "office-person-16967-gursharan-singh",
    "name": "Dr. Gursharan Singh",
    "uid": "16967",
    "designation": "Associate Professor",
    "responsibility": "COD",
    "role": "COD",
    "department_or_subject": null,
    "block": "28",
    "room": "202",
    "seating": "C2",
    "office": null,
    "location_notation": "28-202-C2",
    "parentBlockIds": [
      "block-28"
    ],
    "groupId": "cse-dept",
    "groupName": "School of Computing and Artificial Intelligence",
    "category": "offices",
    "type": "Coordinator of Department (COD) Office",
    "lat": 31.25284540741938,
    "lng": 75.70373386456326,
    "visibleFromZoom": 19,
    "floor": "Block 28, Room 202, Cabin C2",
    "facilities": [
      "Block 28 Academic Block",
      "COD"
    ],
    "tags": [
      "16967",
      "202",
      "28 202 c2",
      "28-202-c2",
      "associate professor",
      "b28",
      "block 28",
      "block 28 room 202",
      "block-28",
      "c2",
      "cabin c2",
      "cod",
      "coordinator of department",
      "dr. gursharan singh",
      "gursharan",
      "gursharan singh",
      "room 202",
      "room 202 block 28",
      "room 202 of block 28",
      "seating c2",
      "singh",
      "uid 16967"
    ],
    "desc": "Dr. Gursharan Singh, Associate Professor. Role: COD. Located in Block 28, Room 202, Cabin C2 (Notation: 28-202-C2).",
    "hours": "8:00 AM - 5:30 PM",
    "phone": "",
    "image": ""
  },
  {
    "id": "office-person-11266-janpreet-singh",
    "name": "Janpreet Singh",
    "uid": "11266",
    "designation": "Assistant Professor",
    "responsibility": "COD",
    "role": "COD",
    "department_or_subject": null,
    "block": "28",
    "room": "202",
    "seating": "C3",
    "office": null,
    "location_notation": "28-202-C3",
    "parentBlockIds": [
      "block-28"
    ],
    "groupId": "cse-dept",
    "groupName": "School of Computing and Artificial Intelligence",
    "category": "offices",
    "type": "Coordinator of Department (COD) Office",
    "lat": 31.25284540741938,
    "lng": 75.70373386456326,
    "visibleFromZoom": 19,
    "floor": "Block 28, Room 202, Cabin C3",
    "facilities": [
      "Block 28 Academic Block",
      "COD"
    ],
    "tags": [
      "11266",
      "202",
      "28 202 c3",
      "28-202-c3",
      "assistant professor",
      "b28",
      "block 28",
      "block 28 room 202",
      "block-28",
      "c3",
      "cabin c3",
      "cod",
      "coordinator of department",
      "janpreet",
      "janpreet singh",
      "room 202",
      "room 202 block 28",
      "room 202 of block 28",
      "seating c3",
      "singh",
      "uid 11266"
    ],
    "desc": "Janpreet Singh, Assistant Professor. Role: COD. Located in Block 28, Room 202, Cabin C3 (Notation: 28-202-C3).",
    "hours": "8:00 AM - 5:30 PM",
    "phone": "",
    "image": ""
  },
  {
    "id": "office-person-14597-robin-prakash-mathur",
    "name": "Dr. Robin Prakash Mathur",
    "uid": "14597",
    "designation": "Associate Professor",
    "responsibility": "COD",
    "role": "COD",
    "department_or_subject": null,
    "block": "28",
    "room": "203",
    "seating": "C1",
    "office": null,
    "location_notation": "28-203-C1",
    "parentBlockIds": [
      "block-28"
    ],
    "groupId": "cse-dept",
    "groupName": "School of Computing and Artificial Intelligence",
    "category": "offices",
    "type": "Coordinator of Department (COD) Office",
    "lat": 31.25284540741938,
    "lng": 75.70373386456326,
    "visibleFromZoom": 19,
    "floor": "Block 28, Room 203, Cabin C1",
    "facilities": [
      "Block 28 Academic Block",
      "COD"
    ],
    "tags": [
      "14597",
      "203",
      "28 203 c1",
      "28-203-c1",
      "associate professor",
      "b28",
      "block 28",
      "block 28 room 203",
      "block-28",
      "c1",
      "cabin c1",
      "cod",
      "coordinator of department",
      "dr. robin prakash mathur",
      "mathur",
      "prakash",
      "robin",
      "robin prakash mathur",
      "room 203",
      "room 203 block 28",
      "room 203 of block 28",
      "seating c1",
      "uid 14597"
    ],
    "desc": "Dr. Robin Prakash Mathur, Associate Professor. Role: COD. Located in Block 28, Room 203, Cabin C1 (Notation: 28-203-C1).",
    "hours": "8:00 AM - 5:30 PM",
    "phone": "",
    "image": ""
  },
  {
    "id": "office-person-32821-neeraj-sharma",
    "name": "Dr. Neeraj Sharma",
    "uid": "32821",
    "designation": "Professor and Dean",
    "responsibility": "HOS",
    "role": "HOS",
    "department_or_subject": null,
    "block": "34",
    "room": "201B",
    "seating": null,
    "office": "HOS Office",
    "location_notation": "34-201B",
    "parentBlockIds": [
      "block-34"
    ],
    "groupId": "cse-dept",
    "groupName": "School of Computer Science & Engineering (CSE)",
    "category": "offices",
    "type": "Head of School (HOS) Office",
    "lat": 31.25148864838823,
    "lng": 75.7047360500708,
    "visibleFromZoom": 19,
    "floor": "Block 34, Room 201B, HOS Office",
    "facilities": [
      "Block 34 Academic Block",
      "HOS Office"
    ],
    "tags": [
      "201b",
      "32821",
      "34 201b",
      "34-201b",
      "b34",
      "block 34",
      "block 34 room 201b",
      "block-34",
      "dr. neeraj sharma",
      "head of school",
      "hos",
      "hos office",
      "neeraj",
      "neeraj sharma",
      "professor and dean",
      "room 201B",
      "room 201b block 34",
      "room 201b of block 34",
      "sharma",
      "uid 32821"
    ],
    "desc": "Dr. Neeraj Sharma, Professor and Dean. Role: HOS. Office: HOS Office. Located in Block 34, Room 201B, HOS Office (Notation: 34-201B).",
    "hours": "8:00 AM - 5:30 PM",
    "phone": "",
    "image": ""
  },
  {
    "id": "office-person-16479-parminder-singh",
    "name": "Dr. Parminder Singh",
    "uid": "16479",
    "designation": "Prof. dy Dean",
    "responsibility": "COS",
    "role": "COS",
    "department_or_subject": null,
    "block": "34",
    "room": "309",
    "seating": null,
    "office": null,
    "location_notation": "34-309",
    "parentBlockIds": [
      "block-34"
    ],
    "groupId": "cse-dept",
    "groupName": "School of Computer Science & Engineering (CSE)",
    "category": "offices",
    "type": "Coordinator of School (COS) Office",
    "lat": 31.25148864838823,
    "lng": 75.7047360500708,
    "visibleFromZoom": 19,
    "floor": "Block 34, Room 309",
    "facilities": [
      "Block 34 Academic Block",
      "COS"
    ],
    "tags": [
      "16479",
      "309",
      "34 309",
      "34-309",
      "b34",
      "block 34",
      "block 34 room 309",
      "block-34",
      "coordinator of school",
      "cos",
      "dr. parminder singh",
      "parminder",
      "parminder singh",
      "prof. dy dean",
      "room 309",
      "room 309 block 34",
      "room 309 of block 34",
      "singh",
      "uid 16479"
    ],
    "desc": "Dr. Parminder Singh, Prof. dy Dean. Role: COS. Located in Block 34, Room 309 (Notation: 34-309).",
    "hours": "8:00 AM - 5:30 PM",
    "phone": "",
    "image": ""
  },
  {
    "id": "office-person-25708-rachit-garg",
    "name": "Dr. Rachit Garg",
    "uid": "25708",
    "designation": "Deputy Dean",
    "responsibility": "Administrator",
    "role": "Administrator",
    "department_or_subject": null,
    "block": "34",
    "room": "206",
    "seating": null,
    "office": "Administrator Office",
    "location_notation": "34-206",
    "parentBlockIds": [
      "block-34"
    ],
    "groupId": "cse-dept",
    "groupName": "School of Computer Science & Engineering (CSE)",
    "category": "offices",
    "type": "Administrator Office",
    "lat": 31.25148864838823,
    "lng": 75.7047360500708,
    "visibleFromZoom": 19,
    "floor": "Block 34, Room 206, Administrator Office",
    "facilities": [
      "Block 34 Academic Block",
      "Administrator Office"
    ],
    "tags": [
      "206",
      "25708",
      "34 206",
      "34-206",
      "admin",
      "administration",
      "administrator",
      "administrator office",
      "b34",
      "block 34",
      "block 34 room 206",
      "block-34",
      "deputy dean",
      "dr. rachit garg",
      "garg",
      "rachit",
      "rachit garg",
      "room 206",
      "room 206 block 34",
      "room 206 of block 34",
      "uid 25708"
    ],
    "desc": "Dr. Rachit Garg, Deputy Dean. Role: Administrator. Office: Administrator Office. Located in Block 34, Room 206, Administrator Office (Notation: 34-206).",
    "hours": "8:00 AM - 5:30 PM",
    "phone": "",
    "image": ""
  },
  {
    "id": "office-person-11427-ajay-kaler",
    "name": "Mr. Ajay Kaler",
    "uid": "11427",
    "designation": "Sr. Officer",
    "responsibility": "Admin",
    "role": "Admin",
    "department_or_subject": null,
    "block": "34",
    "room": "208",
    "seating": null,
    "office": null,
    "location_notation": "34-208",
    "parentBlockIds": [
      "block-34"
    ],
    "groupId": "cse-dept",
    "groupName": "School of Computer Science & Engineering (CSE)",
    "category": "offices",
    "type": "Admin Office",
    "lat": 31.25148864838823,
    "lng": 75.7047360500708,
    "visibleFromZoom": 19,
    "floor": "Block 34, Room 208",
    "facilities": [
      "Block 34 Academic Block",
      "Admin"
    ],
    "tags": [
      "11427",
      "208",
      "34 208",
      "34-208",
      "admin",
      "administration",
      "administrator",
      "ajay",
      "ajay kaler",
      "b34",
      "block 34",
      "block 34 room 208",
      "block-34",
      "kaler",
      "mr. ajay kaler",
      "room 208",
      "room 208 block 34",
      "room 208 of block 34",
      "sr. officer",
      "uid 11427"
    ],
    "desc": "Mr. Ajay Kaler, Sr. Officer. Role: Admin. Located in Block 34, Room 208 (Notation: 34-208).",
    "hours": "8:00 AM - 5:30 PM",
    "phone": "",
    "image": ""
  },
  {
    "id": "office-person-14575-makul-mahajan",
    "name": "Dr. Makul Mahajan",
    "uid": "14575",
    "designation": "Associate Professor",
    "responsibility": "HOD",
    "role": "HOD",
    "department_or_subject": "Data Science and Big Data",
    "block": "34",
    "room": "209",
    "seating": "C1",
    "office": null,
    "location_notation": "34-209-C1",
    "parentBlockIds": [
      "block-34"
    ],
    "groupId": "cse-dept",
    "groupName": "School of Computer Science & Engineering (CSE)",
    "category": "offices",
    "type": "HOD Office (Data Science and Big Data)",
    "lat": 31.25148864838823,
    "lng": 75.7047360500708,
    "visibleFromZoom": 19,
    "floor": "Block 34, Room 209, Cabin C1",
    "facilities": [
      "Block 34 Academic Block",
      "HOD"
    ],
    "tags": [
      "14575",
      "209",
      "34 209 c1",
      "34-209-c1",
      "associate professor",
      "b34",
      "big data",
      "block 34",
      "block 34 room 209",
      "block-34",
      "c1",
      "cabin c1",
      "data science",
      "data science and big data",
      "department head",
      "dr. makul mahajan",
      "ds",
      "head of department",
      "hod",
      "mahajan",
      "makul",
      "makul mahajan",
      "room 209",
      "room 209 block 34",
      "room 209 of block 34",
      "seating c1",
      "uid 14575"
    ],
    "desc": "Dr. Makul Mahajan, Associate Professor. HOD of Data Science and Big Data. Located in Block 34, Room 209, Cabin C1 (Notation: 34-209-C1).",
    "hours": "8:00 AM - 5:30 PM",
    "phone": "",
    "image": ""
  },
  {
    "id": "office-person-12427-harjeet-kaur",
    "name": "Dr. Harjeet Kaur",
    "uid": "12427",
    "designation": "Associate Professor",
    "responsibility": "HOD",
    "role": "HOD",
    "department_or_subject": "Artificial Intelligence and Machine Learning",
    "block": "33",
    "room": "205",
    "seating": "C1",
    "office": null,
    "location_notation": "33-205-C1",
    "parentBlockIds": [
      "block-33"
    ],
    "groupId": "cse-dept",
    "groupName": "School of Computer Science & Engineering (CSE)",
    "category": "offices",
    "type": "HOD Office (Artificial Intelligence and Machine Learning)",
    "lat": 31.25182752424929,
    "lng": 75.70475097721261,
    "visibleFromZoom": 19,
    "floor": "Block 33, Room 205, Cabin C1",
    "facilities": [
      "Block 33 Academic Block",
      "HOD"
    ],
    "tags": [
      "12427",
      "205",
      "33 205 c1",
      "33-205-c1",
      "ai",
      "ai and ml",
      "aiml",
      "artificial intelligence and machine learning",
      "associate professor",
      "b33",
      "block 33",
      "block 33 room 205",
      "block-33",
      "c1",
      "cabin c1",
      "department head",
      "dr. harjeet kaur",
      "harjeet",
      "harjeet kaur",
      "head of department",
      "hod",
      "kaur",
      "machine learning",
      "ml",
      "room 205",
      "room 205 block 33",
      "room 205 of block 33",
      "seating c1",
      "uid 12427"
    ],
    "desc": "Dr. Harjeet Kaur, Associate Professor. HOD of Artificial Intelligence and Machine Learning. Located in Block 33, Room 205, Cabin C1 (Notation: 33-205-C1).",
    "hours": "8:00 AM - 5:30 PM",
    "phone": "",
    "image": ""
  },
  {
    "id": "office-person-12438-manjit-kaur",
    "name": "Dr. Manjit Kaur",
    "uid": "12438",
    "designation": "Professor",
    "responsibility": "HOD",
    "role": "HOD",
    "department_or_subject": "Cloud Computing",
    "block": "34",
    "room": "202",
    "seating": "C1",
    "office": null,
    "location_notation": "34-202-C1",
    "parentBlockIds": [
      "block-34"
    ],
    "groupId": "cse-dept",
    "groupName": "School of Computer Science & Engineering (CSE)",
    "category": "offices",
    "type": "HOD Office (Cloud Computing)",
    "lat": 31.25148864838823,
    "lng": 75.7047360500708,
    "visibleFromZoom": 19,
    "floor": "Block 34, Room 202, Cabin C1",
    "facilities": [
      "Block 34 Academic Block",
      "HOD"
    ],
    "tags": [
      "12438",
      "202",
      "34 202 c1",
      "34-202-c1",
      "b34",
      "block 34",
      "block 34 room 202",
      "block-34",
      "c1",
      "cabin c1",
      "cloud",
      "cloud computing",
      "department head",
      "dr. manjit kaur",
      "head of department",
      "hod",
      "kaur",
      "manjit",
      "manjit kaur",
      "professor",
      "room 202",
      "room 202 block 34",
      "room 202 of block 34",
      "seating c1",
      "uid 12438"
    ],
    "desc": "Dr. Manjit Kaur, Professor. HOD of Cloud Computing. Located in Block 34, Room 202, Cabin C1 (Notation: 34-202-C1).",
    "hours": "8:00 AM - 5:30 PM",
    "phone": "",
    "image": ""
  },
  {
    "id": "office-person-16870-atul-malhotra",
    "name": "Dr. Atul Malhotra",
    "uid": "16870",
    "designation": "Associate Professor",
    "responsibility": "HOD",
    "role": "HOD",
    "department_or_subject": "Network and Cyber Security",
    "block": "34",
    "room": "202",
    "seating": "C3",
    "office": null,
    "location_notation": "34-202-C3",
    "parentBlockIds": [
      "block-34"
    ],
    "groupId": "cse-dept",
    "groupName": "School of Computer Science & Engineering (CSE)",
    "category": "offices",
    "type": "HOD Office (Network and Cyber Security)",
    "lat": 31.25148864838823,
    "lng": 75.7047360500708,
    "visibleFromZoom": 19,
    "floor": "Block 34, Room 202, Cabin C3",
    "facilities": [
      "Block 34 Academic Block",
      "HOD"
    ],
    "tags": [
      "16870",
      "202",
      "34 202 c3",
      "34-202-c3",
      "associate professor",
      "atul",
      "atul malhotra",
      "b34",
      "block 34",
      "block 34 room 202",
      "block-34",
      "c3",
      "cabin c3",
      "cyber",
      "cyber security",
      "department head",
      "dr. atul malhotra",
      "head of department",
      "hod",
      "malhotra",
      "network and cyber security",
      "network security",
      "room 202",
      "room 202 block 34",
      "room 202 of block 34",
      "seating c3",
      "uid 16870"
    ],
    "desc": "Dr. Atul Malhotra, Associate Professor. HOD of Network and Cyber Security. Located in Block 34, Room 202, Cabin C3 (Notation: 34-202-C3).",
    "hours": "8:00 AM - 5:30 PM",
    "phone": "",
    "image": ""
  },
  {
    "id": "office-person-14085-vijay-kumar-garg",
    "name": "Dr. Vijay Kumar Garg",
    "uid": "14085",
    "designation": "Professor",
    "responsibility": "HOD",
    "role": "HOD",
    "department_or_subject": "Programming",
    "block": "36",
    "room": "307",
    "seating": "C1",
    "office": null,
    "location_notation": "36-307-C1",
    "parentBlockIds": [
      "block-36"
    ],
    "groupId": "cse-dept",
    "groupName": "School of Computer Science & Engineering (CSE)",
    "category": "offices",
    "type": "HOD Office (Programming)",
    "lat": 31.2516333779156,
    "lng": 75.70412763243169,
    "visibleFromZoom": 19,
    "floor": "Block 36, Room 307, Cabin C1",
    "facilities": [
      "Block 36 Academic Block",
      "HOD"
    ],
    "tags": [
      "14085",
      "307",
      "36 307 c1",
      "36-307-c1",
      "b36",
      "block 36",
      "block 36 room 307",
      "block-36",
      "c1",
      "cabin c1",
      "coding",
      "department head",
      "dr. vijay kumar garg",
      "garg",
      "head of department",
      "hod",
      "kumar",
      "professor",
      "programming",
      "room 307",
      "room 307 block 36",
      "room 307 of block 36",
      "seating c1",
      "uid 14085",
      "vijay",
      "vijay kumar garg"
    ],
    "desc": "Dr. Vijay Kumar Garg, Professor. HOD of Programming. Located in Block 36, Room 307, Cabin C1 (Notation: 36-307-C1).",
    "hours": "8:00 AM - 5:30 PM",
    "phone": "",
    "image": ""
  },
  {
    "id": "office-person-16870-max-bhatia",
    "name": "Dr. Max Bhatia",
    "uid": "16870",
    "designation": "Associate Professor",
    "responsibility": "HOD",
    "role": "HOD",
    "department_or_subject": "Software Testing and Methodologies",
    "block": "34",
    "room": "207",
    "seating": "C2",
    "office": null,
    "location_notation": "34-207-C2",
    "parentBlockIds": [
      "block-34"
    ],
    "groupId": "cse-dept",
    "groupName": "School of Computer Science & Engineering (CSE)",
    "category": "offices",
    "type": "HOD Office (Software Testing and Methodologies)",
    "lat": 31.25148864838823,
    "lng": 75.7047360500708,
    "visibleFromZoom": 19,
    "floor": "Block 34, Room 207, Cabin C2",
    "facilities": [
      "Block 34 Academic Block",
      "HOD"
    ],
    "tags": [
      "16870",
      "207",
      "34 207 c2",
      "34-207-c2",
      "associate professor",
      "b34",
      "bhatia",
      "block 34",
      "block 34 room 207",
      "block-34",
      "c2",
      "cabin c2",
      "department head",
      "dr. max bhatia",
      "head of department",
      "hod",
      "max",
      "max bhatia",
      "qa",
      "room 207",
      "room 207 block 34",
      "room 207 of block 34",
      "seating c2",
      "software testing",
      "software testing and methodologies",
      "testing",
      "uid 16870"
    ],
    "desc": "Dr. Max Bhatia, Associate Professor. HOD of Software Testing and Methodologies. Located in Block 34, Room 207, Cabin C2 (Notation: 34-207-C2).",
    "hours": "8:00 AM - 5:30 PM",
    "phone": "",
    "image": ""
  },
  {
    "id": "office-person-14623-pushpendra-kumar-pateriya",
    "name": "Pushpendra Kumar Pateriya",
    "uid": "14623",
    "designation": "Assistant Professor",
    "responsibility": "HOD",
    "role": "HOD",
    "department_or_subject": "Full Stack Application Development",
    "block": "34",
    "room": "204",
    "seating": "C1",
    "office": null,
    "location_notation": "34-204-C1",
    "parentBlockIds": [
      "block-34"
    ],
    "groupId": "cse-dept",
    "groupName": "School of Computer Science & Engineering (CSE)",
    "category": "offices",
    "type": "HOD Office (Full Stack Application Development)",
    "lat": 31.25148864838823,
    "lng": 75.7047360500708,
    "visibleFromZoom": 19,
    "floor": "Block 34, Room 204, Cabin C1",
    "facilities": [
      "Block 34 Academic Block",
      "HOD"
    ],
    "tags": [
      "14623",
      "204",
      "34 204 c1",
      "34-204-c1",
      "application development",
      "assistant professor",
      "b34",
      "block 34",
      "block 34 room 204",
      "block-34",
      "c1",
      "cabin c1",
      "department head",
      "full stack",
      "full stack application development",
      "fullstack",
      "head of department",
      "hod",
      "kumar",
      "pateriya",
      "pushpendra",
      "pushpendra kumar pateriya",
      "room 204",
      "room 204 block 34",
      "room 204 of block 34",
      "seating c1",
      "uid 14623",
      "web development"
    ],
    "desc": "Pushpendra Kumar Pateriya, Assistant Professor. HOD of Full Stack Application Development. Located in Block 34, Room 204, Cabin C1 (Notation: 34-204-C1).",
    "hours": "8:00 AM - 5:30 PM",
    "phone": "",
    "image": ""
  },
  {
    "id": "office-person-18364-richa-sharma",
    "name": "Dr. Richa Sharma",
    "uid": "18364",
    "designation": "Associate Professor",
    "responsibility": "HOD",
    "role": "HOD",
    "department_or_subject": "DevOps",
    "block": "36",
    "room": "309A",
    "seating": "C2",
    "office": null,
    "location_notation": "36-309A-C2",
    "parentBlockIds": [
      "block-36"
    ],
    "groupId": "cse-dept",
    "groupName": "School of Computer Science & Engineering (CSE)",
    "category": "offices",
    "type": "HOD Office (DevOps)",
    "lat": 31.2516333779156,
    "lng": 75.70412763243169,
    "visibleFromZoom": 19,
    "floor": "Block 36, Room 309A, Cabin C2",
    "facilities": [
      "Block 36 Academic Block",
      "HOD"
    ],
    "tags": [
      "18364",
      "309a",
      "36 309a c2",
      "36-309a-c2",
      "associate professor",
      "b36",
      "block 36",
      "block 36 room 309a",
      "block-36",
      "c2",
      "cabin c2",
      "ci/cd",
      "department head",
      "devops",
      "dr. richa sharma",
      "head of department",
      "hod",
      "richa",
      "richa sharma",
      "room 309A",
      "room 309a block 36",
      "room 309a of block 36",
      "seating c2",
      "sharma",
      "uid 18364"
    ],
    "desc": "Dr. Richa Sharma, Associate Professor. HOD of DevOps. Located in Block 36, Room 309A, Cabin C2 (Notation: 36-309A-C2).",
    "hours": "8:00 AM - 5:30 PM",
    "phone": "",
    "image": ""
  },
  {
    "id": "office-person-11360-deepak-kumar",
    "name": "Dr. Deepak Kumar",
    "uid": "11360",
    "designation": "Professor and Assistant Dean",
    "responsibility": "HOD",
    "role": "HOD",
    "department_or_subject": "Mathematics",
    "block": "38",
    "room": "301",
    "seating": "C1",
    "office": null,
    "location_notation": "38-301-C1",
    "parentBlockIds": [
      "block-38"
    ],
    "groupId": "cse-dept",
    "groupName": "School of Computer Science & Engineering (CSE)",
    "category": "offices",
    "type": "HOD Office (Mathematics)",
    "lat": 31.252140287536804,
    "lng": 75.70338135340346,
    "visibleFromZoom": 19,
    "floor": "Block 38, Room 301, Cabin C1",
    "facilities": [
      "Block 38 Academic Block",
      "HOD"
    ],
    "tags": [
      "11360",
      "301",
      "38 301 c1",
      "38-301-c1",
      "b38",
      "block 38",
      "block 38 room 301",
      "block-38",
      "c1",
      "cabin c1",
      "deepak",
      "deepak kumar",
      "department head",
      "dr. deepak kumar",
      "head of department",
      "hod",
      "kumar",
      "math",
      "mathematics",
      "maths",
      "professor and assistant dean",
      "room 301",
      "room 301 block 38",
      "room 301 of block 38",
      "seating c1",
      "uid 11360"
    ],
    "desc": "Dr. Deepak Kumar, Professor and Assistant Dean. HOD of Mathematics. Located in Block 38, Room 301, Cabin C1 (Notation: 38-301-C1).",
    "hours": "8:00 AM - 5:30 PM",
    "phone": "",
    "image": ""
  },
  {
    "id": "office-person-13608-gurpinder-singh",
    "name": "Dr. Gurpinder Singh",
    "uid": "13608",
    "designation": "Professor",
    "responsibility": "HOD",
    "role": "HOD",
    "department_or_subject": "Chemistry",
    "block": "33",
    "room": "209",
    "seating": "C1",
    "office": null,
    "location_notation": "33-209-C1",
    "parentBlockIds": [
      "block-33"
    ],
    "groupId": "cse-dept",
    "groupName": "School of Computer Science & Engineering (CSE)",
    "category": "offices",
    "type": "HOD Office (Chemistry)",
    "lat": 31.25182752424929,
    "lng": 75.70475097721261,
    "visibleFromZoom": 19,
    "floor": "Block 33, Room 209, Cabin C1",
    "facilities": [
      "Block 33 Academic Block",
      "HOD"
    ],
    "tags": [
      "13608",
      "209",
      "33 209 c1",
      "33-209-c1",
      "b33",
      "block 33",
      "block 33 room 209",
      "block-33",
      "c1",
      "cabin c1",
      "chem",
      "chemistry",
      "department head",
      "dr. gurpinder singh",
      "gurpinder",
      "gurpinder singh",
      "head of department",
      "hod",
      "professor",
      "room 209",
      "room 209 block 33",
      "room 209 of block 33",
      "seating c1",
      "singh",
      "uid 13608"
    ],
    "desc": "Dr. Gurpinder Singh, Professor. HOD of Chemistry. Located in Block 33, Room 209, Cabin C1 (Notation: 33-209-C1).",
    "hours": "8:00 AM - 5:30 PM",
    "phone": "",
    "image": ""
  },
  {
    "id": "office-person-12284-pawandeep-kaur",
    "name": "Dr. Pawandeep Kaur",
    "uid": "12284",
    "designation": "Associate Professor",
    "responsibility": "HOD",
    "role": "HOD",
    "department_or_subject": "ECE",
    "block": "33",
    "room": "215",
    "seating": "C1",
    "office": null,
    "location_notation": "33-215-C1",
    "parentBlockIds": [
      "block-33"
    ],
    "groupId": "cse-dept",
    "groupName": "School of Computer Science & Engineering (CSE)",
    "category": "offices",
    "type": "HOD Office (ECE)",
    "lat": 31.25182752424929,
    "lng": 75.70475097721261,
    "visibleFromZoom": 19,
    "floor": "Block 33, Room 215, Cabin C1",
    "facilities": [
      "Block 33 Academic Block",
      "HOD"
    ],
    "tags": [
      "12284",
      "215",
      "33 215 c1",
      "33-215-c1",
      "associate professor",
      "b33",
      "block 33",
      "block 33 room 215",
      "block-33",
      "c1",
      "cabin c1",
      "department head",
      "dr. pawandeep kaur",
      "ece",
      "electronics",
      "head of department",
      "hod",
      "kaur",
      "pawandeep",
      "pawandeep kaur",
      "room 215",
      "room 215 block 33",
      "room 215 of block 33",
      "seating c1",
      "uid 12284"
    ],
    "desc": "Dr. Pawandeep Kaur, Associate Professor. HOD of ECE. Located in Block 33, Room 215, Cabin C1 (Notation: 33-215-C1).",
    "hours": "8:00 AM - 5:30 PM",
    "phone": "",
    "image": ""
  },
  {
    "id": "office-person-15312-tejinder-thind",
    "name": "Mr. Tejinder Thind",
    "uid": "15312",
    "designation": "Assistant Professor",
    "responsibility": "HOD",
    "role": "HOD",
    "department_or_subject": "HOL",
    "block": "34",
    "room": "203",
    "seating": "C3",
    "office": null,
    "location_notation": "34-203-C3",
    "parentBlockIds": [
      "block-34"
    ],
    "groupId": "cse-dept",
    "groupName": "School of Computer Science & Engineering (CSE)",
    "category": "offices",
    "type": "HOD Office (HOL)",
    "lat": 31.25148864838823,
    "lng": 75.7047360500708,
    "visibleFromZoom": 19,
    "floor": "Block 34, Room 203, Cabin C3",
    "facilities": [
      "Block 34 Academic Block",
      "HOD"
    ],
    "tags": [
      "15312",
      "203",
      "34 203 c3",
      "34-203-c3",
      "assistant professor",
      "b34",
      "block 34",
      "block 34 room 203",
      "block-34",
      "c3",
      "cabin c3",
      "department head",
      "head of department",
      "head of labs",
      "hod",
      "hol",
      "mr. tejinder thind",
      "room 203",
      "room 203 block 34",
      "room 203 of block 34",
      "seating c3",
      "tejinder",
      "tejinder thind",
      "thind",
      "uid 15312"
    ],
    "desc": "Mr. Tejinder Thind, Assistant Professor. HOD of HOL. Located in Block 34, Room 203, Cabin C3 (Notation: 34-203-C3).",
    "hours": "8:00 AM - 5:30 PM",
    "phone": "",
    "image": ""
  },
  {
    "id": "office-person-11384-amandeep-kaur",
    "name": "Amandeep Kaur",
    "uid": "11384",
    "designation": "Assistant Professor",
    "responsibility": "HOD",
    "role": "HOD",
    "department_or_subject": "Academic Operations",
    "block": "34",
    "room": "205",
    "seating": "C2",
    "office": null,
    "location_notation": "34-205-C2",
    "parentBlockIds": [
      "block-34"
    ],
    "groupId": "cse-dept",
    "groupName": "School of Computer Science & Engineering (CSE)",
    "category": "offices",
    "type": "HOD Office (Academic Operations)",
    "lat": 31.25148864838823,
    "lng": 75.7047360500708,
    "visibleFromZoom": 19,
    "floor": "Block 34, Room 205, Cabin C2",
    "facilities": [
      "Block 34 Academic Block",
      "HOD"
    ],
    "tags": [
      "11384",
      "205",
      "34 205 c2",
      "34-205-c2",
      "acad ops",
      "academic operations",
      "amandeep",
      "amandeep kaur",
      "assistant professor",
      "b34",
      "block 34",
      "block 34 room 205",
      "block-34",
      "c2",
      "cabin c2",
      "department head",
      "head of department",
      "hod",
      "kaur",
      "operations",
      "room 205",
      "room 205 block 34",
      "room 205 of block 34",
      "seating c2",
      "uid 11384"
    ],
    "desc": "Amandeep Kaur, Assistant Professor. HOD of Academic Operations. Located in Block 34, Room 205, Cabin C2 (Notation: 34-205-C2).",
    "hours": "8:00 AM - 5:30 PM",
    "phone": "",
    "image": ""
  },
  {
    "id": "office-person-11361-vikas-verma",
    "name": "Dr. Vikas Verma",
    "uid": "11361",
    "designation": "Associate Professor & Additional Dean",
    "responsibility": "HOS",
    "role": "HOS",
    "department_or_subject": null,
    "block": "26",
    "room": "201A",
    "seating": null,
    "office": "HOS Office",
    "location_notation": "26-201A",
    "parentBlockIds": [
      "block-26"
    ],
    "groupId": "cse-dept",
    "groupName": "School of AI and Emerging Technologies",
    "category": "offices",
    "type": "Head of School (HOS) Office",
    "lat": 31.252861883513926,
    "lng": 75.70289512306216,
    "visibleFromZoom": 19,
    "floor": "Block 26, Room 201A, HOS Office",
    "facilities": [
      "Block 26 Academic Block",
      "HOS Office"
    ],
    "tags": [
      "11361",
      "201a",
      "26 201a",
      "26-201a",
      "associate professor & additional dean",
      "b26",
      "block 26",
      "block 26 room 201a",
      "block-26",
      "dr. vikas verma",
      "head of school",
      "hos",
      "hos office",
      "room 201A",
      "room 201a block 26",
      "room 201a of block 26",
      "uid 11361",
      "verma",
      "vikas",
      "vikas verma"
    ],
    "desc": "Dr. Vikas Verma, Associate Professor & Additional Dean. Role: HOS. Office: HOS Office. Located in Block 26, Room 201A, HOS Office (Notation: 26-201A).",
    "hours": "8:00 AM - 5:30 PM",
    "phone": "",
    "image": ""
  },
  {
    "id": "office-person-14307-raj-karan-singh",
    "name": "Raj Karan Singh",
    "uid": "14307",
    "designation": "Assistant Professor & Assistant Dean",
    "responsibility": "COS",
    "role": "COS",
    "department_or_subject": null,
    "block": "26",
    "room": "207",
    "seating": null,
    "office": "COS Office",
    "location_notation": "26-207",
    "parentBlockIds": [
      "block-26"
    ],
    "groupId": "cse-dept",
    "groupName": "School of AI and Emerging Technologies",
    "category": "offices",
    "type": "Coordinator of School (COS) Office",
    "lat": 31.252861883513926,
    "lng": 75.70289512306216,
    "visibleFromZoom": 19,
    "floor": "Block 26, Room 207, COS Office",
    "facilities": [
      "Block 26 Academic Block",
      "COS Office"
    ],
    "tags": [
      "14307",
      "207",
      "26 207",
      "26-207",
      "assistant professor & assistant dean",
      "b26",
      "block 26",
      "block 26 room 207",
      "block-26",
      "coordinator of school",
      "cos",
      "cos office",
      "karan",
      "raj",
      "raj karan singh",
      "room 207",
      "room 207 block 26",
      "room 207 of block 26",
      "singh",
      "uid 14307"
    ],
    "desc": "Raj Karan Singh, Assistant Professor & Assistant Dean. Role: COS. Office: COS Office. Located in Block 26, Room 207, COS Office (Notation: 26-207).",
    "hours": "8:00 AM - 5:30 PM",
    "phone": "",
    "image": ""
  },
  {
    "id": "office-person-34786-vinay-anand",
    "name": "Dr. Vinay Anand",
    "uid": "34786",
    "designation": "Associate Professor & Administrator",
    "responsibility": "Administrator",
    "role": "Administrator",
    "department_or_subject": null,
    "block": "26",
    "room": "204B",
    "seating": null,
    "office": "Administrator Office",
    "location_notation": "26-204B",
    "parentBlockIds": [
      "block-26"
    ],
    "groupId": "cse-dept",
    "groupName": "School of AI and Emerging Technologies",
    "category": "offices",
    "type": "Administrator Office",
    "lat": 31.252861883513926,
    "lng": 75.70289512306216,
    "visibleFromZoom": 19,
    "floor": "Block 26, Room 204B, Administrator Office",
    "facilities": [
      "Block 26 Academic Block",
      "Administrator Office"
    ],
    "tags": [
      "204b",
      "26 204b",
      "26-204b",
      "34786",
      "admin",
      "administration",
      "administrator",
      "administrator office",
      "anand",
      "associate professor & administrator",
      "b26",
      "block 26",
      "block 26 room 204b",
      "block-26",
      "dr. vinay anand",
      "room 204B",
      "room 204b block 26",
      "room 204b of block 26",
      "uid 34786",
      "vinay",
      "vinay anand"
    ],
    "desc": "Dr. Vinay Anand, Associate Professor & Administrator. Role: Administrator. Office: Administrator Office. Located in Block 26, Room 204B, Administrator Office (Notation: 26-204B).",
    "hours": "8:00 AM - 5:30 PM",
    "phone": "",
    "image": ""
  },
  {
    "id": "office-person-13891-shilpa-sharma",
    "name": "Dr. Shilpa Sharma",
    "uid": "13891",
    "designation": "Professor",
    "responsibility": "COD",
    "role": "COD",
    "department_or_subject": null,
    "block": "25",
    "room": "301",
    "seating": "C2",
    "office": null,
    "location_notation": "25-301-C2",
    "parentBlockIds": [
      "block-25"
    ],
    "groupId": "cse-dept",
    "groupName": "School of AI and Emerging Technologies",
    "category": "offices",
    "type": "Coordinator of Department (COD) Office",
    "lat": 31.25285938442377,
    "lng": 75.70247885462516,
    "visibleFromZoom": 19,
    "floor": "Block 25, Room 301, Cabin C2",
    "facilities": [
      "Block 25 Academic Block",
      "COD"
    ],
    "tags": [
      "13891",
      "25 301 c2",
      "25-301-c2",
      "301",
      "b25",
      "block 25",
      "block 25 room 301",
      "block-25",
      "c2",
      "cabin c2",
      "cod",
      "coordinator of department",
      "dr. shilpa sharma",
      "professor",
      "room 301",
      "room 301 block 25",
      "room 301 of block 25",
      "seating c2",
      "sharma",
      "shilpa",
      "shilpa sharma",
      "uid 13891"
    ],
    "desc": "Dr. Shilpa Sharma, Professor. Role: COD. Located in Block 25, Room 301, Cabin C2 (Notation: 25-301-C2).",
    "hours": "8:00 AM - 5:30 PM",
    "phone": "",
    "image": ""
  },
  {
    "id": "office-person-17451-isha-batra",
    "name": "Dr. Isha Batra",
    "uid": "17451",
    "designation": "Professor",
    "responsibility": "COD",
    "role": "COD",
    "department_or_subject": null,
    "block": "25",
    "room": "301",
    "seating": "C3",
    "office": null,
    "location_notation": "25-301-C3",
    "parentBlockIds": [
      "block-25"
    ],
    "groupId": "cse-dept",
    "groupName": "School of AI and Emerging Technologies",
    "category": "offices",
    "type": "Coordinator of Department (COD) Office",
    "lat": 31.25285938442377,
    "lng": 75.70247885462516,
    "visibleFromZoom": 19,
    "floor": "Block 25, Room 301, Cabin C3",
    "facilities": [
      "Block 25 Academic Block",
      "COD"
    ],
    "tags": [
      "17451",
      "25 301 c3",
      "25-301-c3",
      "301",
      "b25",
      "batra",
      "block 25",
      "block 25 room 301",
      "block-25",
      "c3",
      "cabin c3",
      "cod",
      "coordinator of department",
      "dr. isha batra",
      "isha",
      "isha batra",
      "professor",
      "room 301",
      "room 301 block 25",
      "room 301 of block 25",
      "seating c3",
      "uid 17451"
    ],
    "desc": "Dr. Isha Batra, Professor. Role: COD. Located in Block 25, Room 301, Cabin C3 (Notation: 25-301-C3).",
    "hours": "8:00 AM - 5:30 PM",
    "phone": "",
    "image": ""
  },
  {
    "id": "office-person-14591-virat-deveser",
    "name": "Dr. Virat Deveser",
    "uid": "14591",
    "designation": "Professor",
    "responsibility": "COD",
    "role": "COD",
    "department_or_subject": null,
    "block": "26",
    "room": "202",
    "seating": "C1",
    "office": null,
    "location_notation": "26-202-C1",
    "parentBlockIds": [
      "block-26"
    ],
    "groupId": "cse-dept",
    "groupName": "School of AI and Emerging Technologies",
    "category": "offices",
    "type": "Coordinator of Department (COD) Office",
    "lat": 31.252861883513926,
    "lng": 75.70289512306216,
    "visibleFromZoom": 19,
    "floor": "Block 26, Room 202, Cabin C1",
    "facilities": [
      "Block 26 Academic Block",
      "COD"
    ],
    "tags": [
      "14591",
      "202",
      "26 202 c1",
      "26-202-c1",
      "b26",
      "block 26",
      "block 26 room 202",
      "block-26",
      "c1",
      "cabin c1",
      "cod",
      "coordinator of department",
      "deveser",
      "dr. virat deveser",
      "professor",
      "room 202",
      "room 202 block 26",
      "room 202 of block 26",
      "seating c1",
      "uid 14591",
      "virat",
      "virat deveser"
    ],
    "desc": "Dr. Virat Deveser, Professor. Role: COD. Located in Block 26, Room 202, Cabin C1 (Notation: 26-202-C1).",
    "hours": "8:00 AM - 5:30 PM",
    "phone": "",
    "image": ""
  },
  {
    "id": "office-person-16921-arvind-kumar",
    "name": "Arvind Kumar",
    "uid": "16921",
    "designation": "Assistant Professor",
    "responsibility": "COD",
    "role": "COD",
    "department_or_subject": null,
    "block": "26",
    "room": "202",
    "seating": "C3",
    "office": null,
    "location_notation": "26-202-C3",
    "parentBlockIds": [
      "block-26"
    ],
    "groupId": "cse-dept",
    "groupName": "School of AI and Emerging Technologies",
    "category": "offices",
    "type": "Coordinator of Department (COD) Office",
    "lat": 31.252861883513926,
    "lng": 75.70289512306216,
    "visibleFromZoom": 19,
    "floor": "Block 26, Room 202, Cabin C3",
    "facilities": [
      "Block 26 Academic Block",
      "COD"
    ],
    "tags": [
      "16921",
      "202",
      "26 202 c3",
      "26-202-c3",
      "arvind",
      "arvind kumar",
      "assistant professor",
      "b26",
      "block 26",
      "block 26 room 202",
      "block-26",
      "c3",
      "cabin c3",
      "cod",
      "coordinator of department",
      "kumar",
      "room 202",
      "room 202 block 26",
      "room 202 of block 26",
      "seating c3",
      "uid 16921"
    ],
    "desc": "Arvind Kumar, Assistant Professor. Role: COD. Located in Block 26, Room 202, Cabin C3 (Notation: 26-202-C3).",
    "hours": "8:00 AM - 5:30 PM",
    "phone": "",
    "image": ""
  },
  {
    "id": "office-person-14557-avinash-kaur",
    "name": "Dr. Avinash Kaur",
    "uid": "14557",
    "designation": "Professor",
    "responsibility": "COD",
    "role": "COD",
    "department_or_subject": null,
    "block": "26",
    "room": "203",
    "seating": "C1",
    "office": null,
    "location_notation": "26-203-C1",
    "parentBlockIds": [
      "block-26"
    ],
    "groupId": "cse-dept",
    "groupName": "School of AI and Emerging Technologies",
    "category": "offices",
    "type": "Coordinator of Department (COD) Office",
    "lat": 31.252861883513926,
    "lng": 75.70289512306216,
    "visibleFromZoom": 19,
    "floor": "Block 26, Room 203, Cabin C1",
    "facilities": [
      "Block 26 Academic Block",
      "COD"
    ],
    "tags": [
      "14557",
      "203",
      "26 203 c1",
      "26-203-c1",
      "avinash",
      "avinash kaur",
      "b26",
      "block 26",
      "block 26 room 203",
      "block-26",
      "c1",
      "cabin c1",
      "cod",
      "coordinator of department",
      "dr. avinash kaur",
      "kaur",
      "professor",
      "room 203",
      "room 203 block 26",
      "room 203 of block 26",
      "seating c1",
      "uid 14557"
    ],
    "desc": "Dr. Avinash Kaur, Professor. Role: COD. Located in Block 26, Room 203, Cabin C1 (Notation: 26-203-C1).",
    "hours": "8:00 AM - 5:30 PM",
    "phone": "",
    "image": ""
  },
  {
    "id": "office-person-18758-parampreet-kaur",
    "name": "Dr. Parampreet Kaur",
    "uid": "18758",
    "designation": "Associate Professor",
    "responsibility": "COD",
    "role": "COD",
    "department_or_subject": null,
    "block": "27",
    "room": "203",
    "seating": "C3",
    "office": null,
    "location_notation": "27-203-C3",
    "parentBlockIds": [
      "block-27"
    ],
    "groupId": "cse-dept",
    "groupName": "School of AI and Emerging Technologies",
    "category": "offices",
    "type": "Coordinator of Department (COD) Office",
    "lat": 31.252858651898666,
    "lng": 75.70330718355343,
    "visibleFromZoom": 19,
    "floor": "Block 27, Room 203, Cabin C3",
    "facilities": [
      "Block 27 Academic Block",
      "COD"
    ],
    "tags": [
      "18758",
      "203",
      "27 203 c3",
      "27-203-c3",
      "associate professor",
      "b27",
      "block 27",
      "block 27 room 203",
      "block-27",
      "c3",
      "cabin c3",
      "cod",
      "coordinator of department",
      "dr. parampreet kaur",
      "kaur",
      "parampreet",
      "parampreet kaur",
      "room 203",
      "room 203 block 27",
      "room 203 of block 27",
      "seating c3",
      "uid 18758"
    ],
    "desc": "Dr. Parampreet Kaur, Associate Professor. Role: COD. Located in Block 27, Room 203, Cabin C3 (Notation: 27-203-C3).",
    "hours": "8:00 AM - 5:30 PM",
    "phone": "",
    "image": ""
  },
  {
    "id": "office-person-20260-subhita",
    "name": "Dr. Subhita",
    "uid": "20260",
    "designation": "Assistant Professor",
    "responsibility": "COD",
    "role": "COD",
    "department_or_subject": null,
    "block": "26",
    "room": "205",
    "seating": "C1",
    "office": null,
    "location_notation": "26-205-C1",
    "parentBlockIds": [
      "block-26"
    ],
    "groupId": "cse-dept",
    "groupName": "School of AI and Emerging Technologies",
    "category": "offices",
    "type": "Coordinator of Department (COD) Office",
    "lat": 31.252861883513926,
    "lng": 75.70289512306216,
    "visibleFromZoom": 19,
    "floor": "Block 26, Room 205, Cabin C1",
    "facilities": [
      "Block 26 Academic Block",
      "COD"
    ],
    "tags": [
      "20260",
      "205",
      "26 205 c1",
      "26-205-c1",
      "assistant professor",
      "b26",
      "block 26",
      "block 26 room 205",
      "block-26",
      "c1",
      "cabin c1",
      "cod",
      "coordinator of department",
      "dr. subhita",
      "room 205",
      "room 205 block 26",
      "room 205 of block 26",
      "seating c1",
      "subhita",
      "uid 20260"
    ],
    "desc": "Dr. Subhita, Assistant Professor. Role: COD. Located in Block 26, Room 205, Cabin C1 (Notation: 26-205-C1).",
    "hours": "8:00 AM - 5:30 PM",
    "phone": "",
    "image": ""
  },
  {
    "id": "office-person-11518-gurpreet-singh-bhatia",
    "name": "Dr. Gurpreet Singh Bhatia",
    "uid": "11518",
    "designation": "Associate Professor",
    "responsibility": "COD",
    "role": "COD",
    "department_or_subject": null,
    "block": "38",
    "room": "507",
    "seating": "C1",
    "office": null,
    "location_notation": "38-507-C1",
    "parentBlockIds": [
      "block-38"
    ],
    "groupId": "cse-dept",
    "groupName": "School of AI and Emerging Technologies",
    "category": "offices",
    "type": "Coordinator of Department (COD) Office",
    "lat": 31.252140287536804,
    "lng": 75.70338135340346,
    "visibleFromZoom": 19,
    "floor": "Block 38, Room 507, Cabin C1",
    "facilities": [
      "Block 38 Academic Block",
      "COD"
    ],
    "tags": [
      "11518",
      "38 507 c1",
      "38-507-c1",
      "507",
      "associate professor",
      "b38",
      "bhatia",
      "block 38",
      "block 38 room 507",
      "block-38",
      "c1",
      "cabin c1",
      "cod",
      "coordinator of department",
      "dr. gurpreet singh bhatia",
      "gurpreet",
      "gurpreet singh bhatia",
      "room 507",
      "room 507 block 38",
      "room 507 of block 38",
      "seating c1",
      "singh",
      "uid 11518"
    ],
    "desc": "Dr. Gurpreet Singh Bhatia, Associate Professor. Role: COD. Located in Block 38, Room 507, Cabin C1 (Notation: 38-507-C1).",
    "hours": "8:00 AM - 5:30 PM",
    "phone": "",
    "image": ""
  },
  {
    "id": "office-person-12975-harwant-singh-arri",
    "name": "Dr. Harwant Singh Arri",
    "uid": "12975",
    "designation": "Professor",
    "responsibility": "COD",
    "role": "COD",
    "department_or_subject": null,
    "block": "26",
    "room": "203",
    "seating": "C4",
    "office": null,
    "location_notation": "26-203-C4",
    "parentBlockIds": [
      "block-26"
    ],
    "groupId": "cse-dept",
    "groupName": "School of AI and Emerging Technologies",
    "category": "offices",
    "type": "Coordinator of Department (COD) Office",
    "lat": 31.252861883513926,
    "lng": 75.70289512306216,
    "visibleFromZoom": 19,
    "floor": "Block 26, Room 203, Cabin C4",
    "facilities": [
      "Block 26 Academic Block",
      "COD"
    ],
    "tags": [
      "12975",
      "203",
      "26 203 c4",
      "26-203-c4",
      "arri",
      "b26",
      "block 26",
      "block 26 room 203",
      "block-26",
      "c4",
      "cabin c4",
      "cod",
      "coordinator of department",
      "dr. harwant singh arri",
      "harwant",
      "harwant singh arri",
      "professor",
      "room 203",
      "room 203 block 26",
      "room 203 of block 26",
      "seating c4",
      "singh",
      "uid 12975"
    ],
    "desc": "Dr. Harwant Singh Arri, Professor. Role: COD. Located in Block 26, Room 203, Cabin C4 (Notation: 26-203-C4).",
    "hours": "8:00 AM - 5:30 PM",
    "phone": "",
    "image": ""
  },
  {
    "id": "office-person-13815-timan-kumar",
    "name": "Timan Kumar",
    "uid": "13815",
    "designation": "Officer",
    "responsibility": "Admin Officer",
    "role": "Admin Officer",
    "department_or_subject": null,
    "block": "26",
    "room": "204",
    "seating": null,
    "office": "Admin Office",
    "location_notation": "26-204",
    "parentBlockIds": [
      "block-26"
    ],
    "groupId": "cse-dept",
    "groupName": "School of AI and Emerging Technologies",
    "category": "offices",
    "type": "Admin Officer Office",
    "lat": 31.252861883513926,
    "lng": 75.70289512306216,
    "visibleFromZoom": 19,
    "floor": "Block 26, Room 204, Admin Office",
    "facilities": [
      "Block 26 Academic Block",
      "Admin Office"
    ],
    "tags": [
      "13815",
      "204",
      "26 204",
      "26-204",
      "admin",
      "admin office",
      "admin officer",
      "administration",
      "administrator",
      "b26",
      "block 26",
      "block 26 room 204",
      "block-26",
      "kumar",
      "officer",
      "room 204",
      "room 204 block 26",
      "room 204 of block 26",
      "timan",
      "timan kumar",
      "uid 13815"
    ],
    "desc": "Timan Kumar, Officer. Role: Admin Officer. Office: Admin Office. Located in Block 26, Room 204, Admin Office (Notation: 26-204).",
    "hours": "8:00 AM - 5:30 PM",
    "phone": "",
    "image": ""
  }
];


// Helper Functions
function getLocationsByGroupId(groupId) {
  return getAllCampusLocations().filter(loc => loc.groupId === groupId);
}

function getAllCampusLocations() {
  return [...CAMPUS_LOCATIONS, ...CAMPUS_OFFICES];
}

function getGroupById(groupId) {
  return CAMPUS_GROUPS.find(g => g.id === groupId);
}                                                                                                                                       
